#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EccDHDroidC.Resource", IsApplication=true)]

namespace EccDHDroidC
{


	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{

		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}

		public static void UpdateIdValues()
		{
		}

		public partial class Array
		{

			// aapt resource value: 0x7f050000
			public const int androidcolors = 2131034112;

			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Array()
			{
			}
		}

		public partial class Attribute
		{

			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Attribute()
			{
			}
		}

		public partial class Color
		{

			// aapt resource value: 0x7f040000
			public const int black = 2130968576;

			// aapt resource value: 0x7f040003
			public const int blue = 2130968579;

			// aapt resource value: 0x7f040002
			public const int cyan = 2130968578;

			// aapt resource value: 0x7f040008
			public const int darkblue = 2130968584;

			// aapt resource value: 0x7f04000a
			public const int darkgreen = 2130968586;

			// aapt resource value: 0x7f04000b
			public const int darkorange = 2130968587;

			// aapt resource value: 0x7f040009
			public const int darkpurple = 2130968585;

			// aapt resource value: 0x7f04000c
			public const int darkred = 2130968588;

			// aapt resource value: 0x7f040005
			public const int green = 2130968581;

			// aapt resource value: 0x7f040006
			public const int orange = 2130968582;

			// aapt resource value: 0x7f040004
			public const int purple = 2130968580;

			// aapt resource value: 0x7f040007
			public const int red = 2130968583;

			// aapt resource value: 0x7f040001
			public const int yellow = 2130968577;

			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Color()
			{
			}
		}

		public partial class Id
		{

			// aapt resource value: 0x7f070000
			public const int a1b = 2131165184;

			// aapt resource value: 0x7f070001
			public const int a1t = 2131165185;

			// aapt resource value: 0x7f070002
			public const int a2b = 2131165186;

			// aapt resource value: 0x7f070003
			public const int a2t = 2131165187;

			// aapt resource value: 0x7f070004
			public const int a3b = 2131165188;

			// aapt resource value: 0x7f070005
			public const int a3t = 2131165189;

			// aapt resource value: 0x7f07000c
			public const int a4b = 2131165196;

			// aapt resource value: 0x7f07000d
			public const int a4t = 2131165197;

			// aapt resource value: 0x7f070006
			public const int b1b = 2131165190;

			// aapt resource value: 0x7f070007
			public const int b1t = 2131165191;

			// aapt resource value: 0x7f070008
			public const int b2b = 2131165192;

			// aapt resource value: 0x7f070009
			public const int b2t = 2131165193;

			// aapt resource value: 0x7f07000a
			public const int b3b = 2131165194;

			// aapt resource value: 0x7f07000b
			public const int b3t = 2131165195;

			// aapt resource value: 0x7f07000e
			public const int b4b = 2131165198;

			// aapt resource value: 0x7f07000f
			public const int b4t = 2131165199;

			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Id()
			{
			}
		}

		public partial class Layout
		{

			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;

			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Layout()
			{
			}
		}

		public partial class Mipmap
		{

			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;

			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private Mipmap()
			{
			}
		}

		public partial class String
		{

			// aapt resource value: 0x7f060001
			public const int a1 = 2131099649;

			// aapt resource value: 0x7f060002
			public const int a2 = 2131099650;

			// aapt resource value: 0x7f060003
			public const int a3 = 2131099651;

			// aapt resource value: 0x7f060007
			public const int a4 = 2131099655;

			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;

			// aapt resource value: 0x7f060004
			public const int b1 = 2131099652;

			// aapt resource value: 0x7f060005
			public const int b2 = 2131099653;

			// aapt resource value: 0x7f060006
			public const int b3 = 2131099654;

			// aapt resource value: 0x7f060008
			public const int b4 = 2131099656;

			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}

			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
